### ISSUE TITLE
The skeleton installer fails in the post-update-cmd phase

### ISSUE THREAD

**Issue by settermjd** [mezzio/mezzio-skeleton#162]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 3.15.0

#### Summary

After providing responses to all of the skeleton installer's questions, the install fails because `Mezzio\Helper\ConfigProvider` is registered more than once.

#### Current behavior

In the post-update-cmd phase of the installation, output such as the example below is printed to the terminal, showing that `Mezzio\Helper\ConfigProvider` is registered more than once, breaking the call to `php bin/clear-config-cache.php`.

```bash
> php bin/clear-config-cache.php
PHP Fatal error:  Uncaught Laminas\ConfigAggregator\InvalidConfigProviderException: Mezzio\Helper\ConfigProvider is registered more than once. Config providers should be unique. In case a specific order is required, please double check before deleting the duplicate(s). in /home/dev/projects/mezzio//stock-valuation-tracker/vendor/laminas/laminas-config-aggregator/src/InvalidConfigProviderException.php:15
Stack trace:
#0 /home/dev/projects/mezzio//stock-valuation-tracker/vendor/laminas/laminas-config-aggregator/src/ConfigAggregator.php(118): Laminas\ConfigAggregator\InvalidConfigProviderException::fromDuplicateProvider()
#1 /home/dev/projects/mezzio//stock-valuation-tracker/vendor/laminas/laminas-config-aggregator/src/ConfigAggregator.php(85): Laminas\ConfigAggregator\ConfigAggregator->validateNoDuplicateProviders()
#2 /home/dev/projects/mezzio//stock-valuation-tracker/config/config.php(49): Laminas\ConfigAggregator\ConfigAggregator->__construct()
#3 /home/dev/projects/mezzio//stock-valuation-tracker/bin/clear-config-cache.php(9): include('...')
#4 {main}
  thrown in /home/dev/projects/mezzio/stock-valuation-tracker/vendor/laminas/laminas-config-aggregator/src/InvalidConfigProviderException.php on line 15
Script php bin/clear-config-cache.php handling the clear-config-cache event returned with error code 255
Script @clear-config-cache was called via post-update-cmd
```

#### How to reproduce

- Start off by running `composer create-project mezzio/mezzio-skeleton <package name>`, where `<package name>` is a name of your choosing
- Answer the prompts as you prefer
- After the final question is answered, the installer will fail with output similar to the example provided above

#### Expected behavior

The installer should complete without errors or failures.

**Comment by froschdesign** [comment]
Duplicate of #161
